[package]
name = "reql"
description = "A native RethinkDB driver"
version = "0.0.9-pre"
license = "MIT/Apache-2.0"
repository = "https://github.com/rust-rethinkdb/reql"
documentation = "https://docs.rs/reql"
readme = "README.md"
keywords = ["database", "rethinkdb", "reql", "driver"]
categories = ["database"]
authors = ["rushmorem <rushmore@webenchanter.com>"]
build = "build/main.rs"

[badges]
travis-ci = { repository = "rust-rethinkdb/reql" }

[dependencies]
protobuf = "1.2"
slog = "2.0"
serde = "1.0"
serde_json = "1.0"
ql2 = "1.1"
derive-error = "0.0.3"
proc-macro-hack = { git = "https://github.com/opensourcegeek/proc-macro-hack.git" }
lazy_static = "0.2"
serde_derive = "1.0"
r2d2 = "0.7"
byteorder = "1.0"
bufstream = "0.1"
scram = "0.2"
tokio-core = "0.1"
futures = "0.1"
parking_lot = "0.4"
ordermap = "0.2"
reql-derive = { version = "0.0.6", path = "./derive" }
reql-types = { version = "0.0.1", path = "./types" }
uuid = { version = "0.5", features = ["use_std", "v4", "serde"] }

[dev-dependencies]
slog-term = "2.0"

[build-dependencies]
serde = "1.0"
serde_derive = "1.0"
serde_yaml = "0.7"
nom = "3.0"
